#-------------------------------------------------------------------------------
#
# Copyright 2010 Duane Merrill
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 
# 
#-------------------------------------------------------------------------------
 
#-------------------------------------------------------------------------------
# Build script for project
#-------------------------------------------------------------------------------

EXECUTABLE		:= test_radix_sort

CUFILES_sm_13	:= test_radix_sort.cu


CU_DEPS 						:= \
	srts_radix_sort.cu 			   \
	srts_radix_sort_kernel.cu	   \
	srts_verifier.cu

CCFILES			:= 


# Include common targets and rules
include ../../common/common.mk

